skjolber/3d-bin-container-packing

README.md, src/main/java/com/github/skjolberg/packing/BoxItem.java, src/main/java/com/github/skjolberg/packing/BruteForcePackager.java, src/main/java/com/github/skjolberg/packing/Container.java, src/main/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager.java, src/main/java/com/github/skjolberg/packing/Packager.java, src/main/java/com/github/skjolberg/packing/PermutationRotationIterator.java, src/test/java/com/github/skjolberg/packing/AbstractPackagerTest.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerRuntimeEstimator.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerTest.java, src/test/java/com/github/skjolberg/packing/ContainerTest.java, src/test/java/com/github/skjolberg/packing/DimensionTest.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager2DTest.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager3DTest.java, src/test/java/com/github/skjolberg/packing/PackagerCombinationDemo.java, src/test/java/com/github/skjolberg/packing/PackagerTest.java, src/test/java/com/github/skjolberg/packing/PermutationRotationIteratorTest.java, src/test/java/com/github/skjolberg/packing/SpaceTest.java
Add count to a box type. This makes the brute-force packager better.
=> Order Item support

src/main/java/com/github/skjolberg/packing/PermutationRotationIterator.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerRuntimeEstimator.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerTest.java
@othp seems the box was incorrectly looking up the rotation.
=> Fix for issue 11

src/test/java/com/github/skjolberg/packing/BruteForcePackagerTest.java
Here is the solution expected: (obtained from https://www.3dbinpacking.com/en/)
```
{
"bins": [
{
"w": 152,
"h": 252,
"d": 58,
"max_wg": 528,
"id": "Bin1"
}
],
"items": [
{
"w": 73,
"h": 82,
"d": 54,
"q": 1,
"vr": 1,
"wg": 88,
"id": "Item1"
},
{
"w": 72,
"h": 80,
"d": 57,
"q": 1,
"vr": 1,
"wg": 88,
"id": "Item2"
}, {
"w": 73,
"h": 83,
"d": 53,
"q": 1,
"vr": 1,
"wg": 88,
"id": "Item3"
},{
"w": 71,
"h": 83,
"d": 53,
"q": 1,
"vr": 1,
"wg": 88,
"id": "Item4"
},{
"w": 74,
"h": 83,
"d": 53,
"q": 1,
"vr": 1,
"wg": 88,
"id": "Item5"
}  , {
"w": 74,
"h": 82,
"d": 54,
"q": 1,
"vr": 1,
"wg": 88,
"id": "Item6"
}
],
"username": "xxx",
"api_key": "xxx",
"params": {
"images_background_color": "255,255,255",
"images_bin_border_color": "59,59,59",
"images_bin_fill_color": "230,230,230", …
```
=> new unit testing showing a bug in BruteForcePackager

src/main/java/com/github/skjolberg/packing/Container.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerTest.java, src/test/java/com/github/skjolberg/packing/ContainerTest.java
=> compute actually used space (bounding box)

src/test/java/com/github/skjolberg/packing/BruteForcePropertyBasedTests.java
another PBT for when you fixed the previous bug.
We probably need to tune down the amount of boxes this tries to brute-force pack, 1000 (even if identical) is probably too ambitious ...
=> test packing several identical boxes in just-fitting containers

.editorconfig, src/test/java/com/github/skjolberg/packing/BruteForcePropertyBasedTests.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager3DTest.java
This packaging has a solution (found by https://www.3dbinpacking.com/en/)
but the LAFF is pretty far, only 6 boxes are packed
Any idea how we can better results (ie more boxes packed) ?
=>  test for LAFF with about 20 products

.gitignore, src/main/java/com/github/skjolberg/packing/BinarySearchIterator.java, src/main/java/com/github/skjolberg/packing/Box.java, src/main/java/com/github/skjolberg/packing/BruteForcePackager.java, src/main/java/com/github/skjolberg/packing/Container.java, src/main/java/com/github/skjolberg/packing/Dimension.java, src/main/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager.java, src/main/java/com/github/skjolberg/packing/Level.java, src/main/java/com/github/skjolberg/packing/Packager.java, src/main/java/com/github/skjolberg/packing/PermutationRotationIterator.java, src/main/java/com/github/skjolberg/packing/PermutationRotationState.java, src/main/java/com/github/skjolberg/packing/Placement.java, src/main/java/com/github/skjolberg/packing/Space.java, src/test/java/com/github/skjolberg/packing/AbstractPackagerTest.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerRuntimeEstimator.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerTest.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager2DTest.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager3DTest.java, src/test/java/com/github/skjolberg/packing/PackagerCombinationDemo.java, src/test/java/com/github/skjolberg/packing/PackagerTest.java, src/test/java/com/github/skjolberg/packing/PermutationRotationIteratorTest.java
My IDE kept complaining about dead code so I removed it :)
=> removed some dead code

src/main/java/com/github/skjolberg/packing/BruteForcePackager.java, src/main/java/com/github/skjolberg/packing/Constants.java, src/main/java/com/github/skjolberg/packing/Container.java, src/main/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager.java, src/main/java/com/github/skjolberg/packing/Packager.java, src/main/java/com/github/skjolberg/packing/impl/Adapter.java, src/main/java/com/github/skjolberg/packing/impl/PermutationRotationIterator.java, src/test/java/com/github/skjolberg/packing/AbstractPackagerTest.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerTest.java, src/test/java/com/github/skjolberg/packing/BruteForcePropertyBasedTests.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager2DTest.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager3DTest.java, src/test/java/com/github/skjolberg/packing/PackagerTest.java, src/test/java/com/github/skjolberg/packing/impl/BruteForcePackagerRuntimeEstimator.java
this is a followup to #50 with the functional interface
=>  Implement a minimal `interruptible` feature

pom.xml, src/main/java/com/github/skjolberg/packing/BruteForcePackager.java, src/main/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager.java, src/test/java/com/github/skjolberg/packing/BruteForcePackagerTest.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager3DTest.java
See issue #78 - the z position is set to an incorrect value.
=> Fix for issue #78

src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager2DTest.java, src/test/java/com/github/skjolberg/packing/LargestAreaFitFirstPackager3DTest.java
Hey @skjolber, There is another test case where the issue #83 still exists. Adding the unit test case in this PR
=> Issue #83 still exists.

README.md
The previous link is dead. I found this link on a DDG search query. Author and tittle are the same, please confirm it is indeed the same paper before merging.
=> Fixed broken link for algorithm paper

.gitignore, .travis.yml, core/pom.xml, core/src/main/java9/module-info.java, jmh/pom.xml, jmh/src/main/java/com/github/skjolber/jmh/PackagerBenchmark.java, jmh/src/main/java/com/github/skjolber/jmh/PackagerState.java, jmh/src/main/java9/module-info.java, pom.xml
=> Multi-release jar

core/src/main/java/com/github/skjolber/packing/BruteForcePackager.java, core/src/main/java/com/github/skjolber/packing/Packager.java, core/src/main/java/com/github/skjolber/packing/impl/DefaultPermutationRotationIterator.java, core/src/main/java/com/github/skjolber/packing/impl/EmptyPackResult.java, core/src/test/java/com/github/skjolber/packing/BruteForcePackagerTest.java
The problem was a modification of an argument list
=> Fix issue 245

core/src/main/java/com/github/skjolber/packing/LargestAreaFitFirstPackagerBuilder.java, core/src/test/java/com/github/skjolber/packing/LargestAreaFitFirstPackager3DTest.java
My proposal for issue #251. Had this problem myself and nearly missed the complications implicated by the missing 3d rotation. If the proposal misses a key point I'm happy to change it.
Please feel free to comment.
=> solved #251 added default value true to laff builder rotate3d

README.md, core/src/main/java/com/github/skjolber/packing/packer/laff/FastLargestAreaFitFirstPackager.java, core/src/main/java/com/github/skjolber/packing/packer/laff/LargestAreaFitFirstPackager.java, core/src/test/java/com/github/skjolber/packing/packer/laff/LargestAreaFitFirstPackagerTest.java, visualizer/packaging/src/test/java/com/github/skjolber/packing/visualizer/packaging/VisualizationTest.java
=> Visualize + fix issue 433

api/src/main/java/com/github/skjolber/packing/api/ep/Point2D.java, api/src/main/java/com/github/skjolber/packing/api/ep/Point3D.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/AbstractBruteForcePackager.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/FastBruteForcePackager.java, core/src/test/java/com/github/skjolber/packing/packer/bruteforce/BruteForcePackagerTest.java, extreme-points/pom.xml, extreme-points/src/main/java/com/github/skjolber/packing/ep/points2d/ExtremePoints2D.java, extreme-points/src/main/java/com/github/skjolber/packing/ep/points3d/ExtremePoints3D.java, extreme-points/src/main/java/com/github/skjolber/packing/ep/points3d/Point3DFlagList.java, extreme-points/src/test/java/com/github/skjolber/packing/points2d/ExtremePoints2DTest.java, jmh/src/main/java/com/github/skjolber/packing/jmh/ep/ExtremePointsBenchmark.java, pom.xml, visualizer/packaging/src/test/java/com/github/skjolber/packing/visualizer/packaging/VisualizationTest.java
Improve performance of `eclipses` methods, as they are on o(n*n) compexity.
=> Optimize bruteforce

core/src/main/java/com/github/skjolber/packing/iterator/AbstractPermutationRotationIterator.java, core/src/main/java/com/github/skjolber/packing/iterator/PermutationRotationIterator.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/AbstractBruteForcePackager.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/ExtremePoints3DStack.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/FastBruteForcePackager.java, core/src/main/java/com/github/skjolber/packing/packer/laff/FastLargestAreaFitFirstPackager.java, core/src/main/java/com/github/skjolber/packing/packer/laff/LargestAreaFitFirstPackager.java, core/src/main/java/com/github/skjolber/packing/packer/plain/AbstractPlainPackager.java, core/src/main/java/com/github/skjolber/packing/packer/plain/PlainPackager.java, core/src/test/java/com/github/skjolber/packing/packer/bruteforce/FastBruteForcePackagerTest.java, extreme-points/src/main/java/com/github/skjolber/packing/ep/points2d/ExtremePoints2D.java, extreme-points/src/main/java/com/github/skjolber/packing/ep/points3d/ExtremePoints3D.java, jmh/src/main/java/com/github/skjolber/packing/jmh/EgyPackagerBenchmark.java, jmh/src/main/java/com/github/skjolber/packing/jmh/EgyPackagerState.java
Performance improvement for some cases.
=> Use minimum area and volume2

api/pom.xml, core/pom.xml, eclipse-formatter.xml, extreme-points/pom.xml, jmh/pom.xml, pom.xml, test/pom.xml
Tidy up formatting - it is suffering from tabs vs spaces
=> Add spotless formatter

core/src/main/java/com/github/skjolber/packing/iterator/DefaultPermutationRotationIterator.java, core/src/main/java/com/github/skjolber/packing/iterator/ParallelPermutationRotationIterator.java, core/src/main/java/com/github/skjolber/packing/iterator/ParallelPermutationRotationIteratorList.java, core/src/main/java/com/github/skjolber/packing/packer/AbstractPackager.java, core/src/main/java/com/github/skjolber/packing/packer/PackagerAdapter.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/AbstractBruteForcePackagerAdapter.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/BruteForcePackager.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/FastBruteForcePackager.java, core/src/main/java/com/github/skjolber/packing/packer/bruteforce/ParallelBruteForcePackager.java, core/src/test/java/com/github/skjolber/packing/iterator/PermutationRotationIteratorTest.java, core/src/test/java/com/github/skjolber/packing/packer/bruteforce/AbstractBruteForcePackagerTest.java, core/src/test/java/com/github/skjolber/packing/packer/bruteforce/BruteForcePackagerTest.java, core/src/test/java/com/github/skjolber/packing/packer/bruteforce/FastBruteForcePackagerTest.java, core/src/test/java/com/github/skjolber/packing/packer/bruteforce/ParallelBruteForcePackagerTest.java
Extract common brute force packager adapter code
=> Improve multi container results

api/src/main/java/com/github/skjolber/packing/api/ContainerItem.java, core/src/main/java/com/github/skjolber/packing/packer/AbstractPackagerAdapter.java, core/src/test/java/com/github/skjolber/packing/packer/AbstractPackagerAdapterTest.java, core/src/test/java/com/github/skjolber/packing/packer/bruteforce/FastBruteForcePackagerTest.java, core/src/test/java/com/github/skjolber/packing/packer/laff/FastLargestAreaFitFirstPackagerTest.java
Fix https://github.com/skjolber/3d-bin-container-packing/issues/1022
* avoid long overflow 
* improve max volume / weight calculation
* various minor adjustments
=> Use BigInteger to sanity-check max volume / max weight, calculate real remaining max volume
